add license headers

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -18,10 +18,51 @@ name: github-checks
 on:
   pull_request:
     branches:
-      - develop
-      - release/**
+      - '**'
 
 jobs:
+  license:
+    name: license
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v2
+      - uses: jitterbit/get-changed-files@v1
+        id: files
+        continue-on-error: true
+      - name: Check license
+        run: |
+          set +e # make this step proceed even if a command returns non-zero
+          license_headers=.github/workflows/license_headers
+          result="PASS"
+
+          for f in ${{ steps.files.outputs.added_modified }}; do
+            if [ -d "$f" ]; then
+              continue
+            fi
+
+            ext=$(expr $f : ".*\(\..*\)")
+            case $ext in
+            .java) true;; # only java files are checked.
+            *) continue ;; # skip others
+            esac
+
+            result_for_f="FAIL"
+            for header in `find $license_headers -type f`; do
+              line_cnt=`wc -l < $header`
+              head -n $line_cnt $f | diff -w - $header
+              if [ $? -eq 0 ]; then
+                result_for_f="PASS"
+                break
+              fi
+            done
+
+            echo "$f: $result_for_f"
+            if [ "$result_for_f" = "FAIL" ]; then
+              result="FAIL"
+            fi
+          done
+
+          test $result = "PASS" # if non-zero, fail
   pr-style:
     name: pr-style
     runs-on: ubuntu-latest
